start notebook after the workers, it seems the tunnel gets killed otherwise...

diff --git a/aws-slurm-ipcluster/start_ipcluster b/aws-slurm-ipcluster/start_ipcluster
--- a/aws-slurm-ipcluster/start_ipcluster
+++ b/aws-slurm-ipcluster/start_ipcluster
@@ -39,18 +39,6 @@ mkdir -p "$LOGD"
 /bin/rm -f "$LOGD/ipcluster-logs"
 /bin/ln -s "$HOME"/.ipython/profile_default/log "$LOGD/ipcluster-logs"
 
-
-echo "Starting jupyter notebook..."
-jupyter notebook --no-browser >& "$LOGD"/jupyter-notebook.log &
-sleep 5
-LINK=$(jupyter notebook list | grep http | cut -d ' ' -f 1)
-if [ -z "$LINK" ]; then
-    echo "Could not start jupyter notebook!"
-    exit 1
-fi
-echo "You can connect to the notebook on your local machine by pointing a browser to:"
-echo "$LINK"
-
 echo "Starting workers..."
 # start the controller and the first worker
 ipcluster start -n 1 --daemonize
@@ -79,3 +67,15 @@ while [ "$pending" -ne 0 ]; do
     running=$(get_running)
 done
 echo "All workers have been started [elapsed: $WAITTIME s]!"
+
+echo "Starting jupyter notebook..."
+jupyter notebook --no-browser >& "$LOGD"/jupyter-notebook.log &
+sleep 5
+LINK=$(jupyter notebook list | grep http | cut -d ' ' -f 1)
+if [ -z "$LINK" ]; then
+    echo "Could not start jupyter notebook!"
+    exit 1
+fi
+echo "You can connect to the notebook on your local machine by pointing a browser to:"
+echo "$LINK"
+
